version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_ml
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: superheroes_etl
    ports:
      - "5435:5432" # Puerto HOST:CONTENEDOR
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ml_network

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_ml
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: superheroes_etl
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ml_network

volumes:
  postgres_data:

networks:
  ml_network:
    driver: bridge