"""Initial migration: Create tables for superheroes ETL

Revision ID: c667a3b222a9
Revises: 
Create Date: 2026-04-04 21:35:33.213659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c667a3b222a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=False),
    sa.Column('registros_guardados', sa.Integer(), nullable=False),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metricas_etl_fecha_ejecucion'), 'metricas_etl', ['fecha_ejecucion'], unique=False)
    op.create_table('superheroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('superhero_api_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('nombre_real', sa.String(length=200), nullable=True),
    sa.Column('editorial', sa.String(length=100), nullable=True),
    sa.Column('alineacion', sa.String(length=50), nullable=True),
    sa.Column('lugar_nacimiento', sa.String(length=255), nullable=True),
    sa.Column('primera_aparicion', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superheroes_nombre'), 'superheroes', ['nombre'], unique=False)
    op.create_index(op.f('ix_superheroes_superhero_api_id'), 'superheroes', ['superhero_api_id'], unique=True)
    op.create_table('apariencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('superhero_id', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('raza', sa.String(length=100), nullable=True),
    sa.Column('altura', sa.String(length=50), nullable=True),
    sa.Column('peso', sa.String(length=50), nullable=True),
    sa.Column('color_ojos', sa.String(length=50), nullable=True),
    sa.Column('color_cabello', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['superhero_id'], ['superheroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apariencia_superhero_id'), 'apariencia', ['superhero_id'], unique=True)
    op.create_table('powerstats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('superhero_id', sa.Integer(), nullable=False),
    sa.Column('inteligencia', sa.Integer(), nullable=True),
    sa.Column('fuerza', sa.Integer(), nullable=True),
    sa.Column('velocidad', sa.Integer(), nullable=True),
    sa.Column('durabilidad', sa.Integer(), nullable=True),
    sa.Column('poder', sa.Integer(), nullable=True),
    sa.Column('combate', sa.Integer(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['superhero_id'], ['superheroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_powerstats_hero_fecha', 'powerstats', ['superhero_id', 'fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_powerstats_fecha_extraccion'), 'powerstats', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_powerstats_superhero_id'), 'powerstats', ['superhero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_powerstats_superhero_id'), table_name='powerstats')
    op.drop_index(op.f('ix_powerstats_fecha_extraccion'), table_name='powerstats')
    op.drop_index('idx_powerstats_hero_fecha', table_name='powerstats')
    op.drop_table('powerstats')
    op.drop_index(op.f('ix_apariencia_superhero_id'), table_name='apariencia')
    op.drop_table('apariencia')
    op.drop_index(op.f('ix_superheroes_superhero_api_id'), table_name='superheroes')
    op.drop_index(op.f('ix_superheroes_nombre'), table_name='superheroes')
    op.drop_table('superheroes')
    op.drop_index(op.f('ix_metricas_etl_fecha_ejecucion'), table_name='metricas_etl')
    op.drop_table('metricas_etl')
    # ### end Alembic commands ###
